define([
    "./GadgetSpace",
    "./PageRoutingGadgetSpace",
    "./SmithyProxy",
    "./dojoviews/DojoViewFactory",
    "./lifecycle/LifeCycle",
    "./GadgetSpace",
    "./schema/channels/AreaStatusChange",
    "./schema/channels/GadgetRegistrationEvent",
    "./schema/channels/GadgetSpaceStatusChange",
    "./schema/channels/GadgetStatusChange",
    "./schema/channels/SlagChange",
    "./schema/models/GadgetAreaSchema",
    "./schema/models/GadgetDescriptorSchema",
    "./schema/models/GadgetSchema",
    "./schema/models/GadgetSpaceSchema",
    "./ToolGadget"
], function () {
});